<a href="https://colab.research.google.com/github/paulgureghian/Deep_Learning_with_Keras/blob/master/Bike_Buyer_Keras_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Created by Paul A. Gureghian in Jan 2019.**

**I will use Keras to build a DL model to predict  whether someone will buy a bike**
**based on some predictor variables.**

This notebook focuses on a specific sub-field of machine learning called **predictive modeling.**

Within predicitve modeling is a speciality or another sub-field called **deep learning.**

I will craft a binary deep learning model with a library called Keras. 

It will just predict one of two outcomes: positive or negative. 

I will use a 'Bike Buyer' csv dataset.  BBCN. 

In [13]:
### Mount Google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Step 1. Import our packages.

In [0]:
### Import packages
import numpy as np
import pandas as pd
from keras.layers import Dense
from keras.models import Sequential

# Step 2.  Set our random seed.


**The only purpose of seeding is to get the same result on the same data.**

In [0]:
### Set random seed
seed = 9
np.random.seed(seed)

# Step 3.  Import the data set.


**I define a variable called 'bbcn' and put the data set in it.**  

In [16]:
### Import the dataset
bike_buyer = ('/content/drive/My Drive/Bike_Buyer/bike_buyer.csv')
df = pd.read_csv(bike_buyer)
df.head()

MaritalStatus  Gender  YearlyIncome  TotalChildren  NumberChildrenAtHome  \
0              5       1           9.0              2                     0   
1              5       1           6.0              3                     3   
2              5       1           6.0              3                     3   
3              5       2           7.0              0                     0   
4              5       2           8.0              5                     5   

   EnglishEducation  HouseOwnerFlag  NumberCarsOwned  CommuteDistance  Region  \
0                 5               1                0                2       2   
1                 5               0                1                1       2   
2                 5               1                1                5       2   
3                 5               0                1               10       2   
4                 5               1                4                2       2   

   Age  BikeBuyer  
0    5          1  
1    4          1  
2    4          1  
3    5          1  
4    5          1

# Step 4.  Split the Output Variables.


**The first thing I will do is put the data in an array data type structure.** 

In [17]:
### Store dataset values
array = df.values
print(array)

[[5. 1. 9. ... 2. 5. 1.]
 [5. 1. 6. ... 2. 4. 1.]
 [5. 1. 6. ... 2. 4. 1.]
 ...
 [3. 2. 4. ... 3. 5. 0.]
 [3. 1. 4. ... 1. 4. 0.]
 [3. 1. 4. ... 1. 4. 0.]]


**Define X(features) and y(target).**

In [18]:
### Define X and y
X = array[:,0:11] 
y = array[:,11]

print('X_shape:\n', X.shape, '\n')
print('X:\n', X, '\n')
print('y_shape:\n', y.shape, '\n')
print('y:\n', y)

X_shape:
 (500, 11) 

X:
 [[5. 1. 9. ... 2. 2. 5.]
 [5. 1. 6. ... 1. 2. 4.]
 [5. 1. 6. ... 5. 2. 4.]
 ...
 [3. 2. 4. ... 2. 3. 5.]
 [3. 1. 4. ... 2. 1. 4.]
 [3. 1. 4. ... 2. 1. 4.]] 

y_shape:
 (500,) 

y:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 1. 0.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1.
 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0.
 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1.
 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0.
 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1.
 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0.

In [19]:
### Print dataset
df.head()

MaritalStatus  Gender  YearlyIncome  TotalChildren  NumberChildrenAtHome  \
0              5       1           9.0              2                     0   
1              5       1           6.0              3                     3   
2              5       1           6.0              3                     3   
3              5       2           7.0              0                     0   
4              5       2           8.0              5                     5   

   EnglishEducation  HouseOwnerFlag  NumberCarsOwned  CommuteDistance  Region  \
0                 5               1                0                2       2   
1                 5               0                1                1       2   
2                 5               1                1                5       2   
3                 5               0                1               10       2   
4                 5               1                4                2       2   

   Age  BikeBuyer  
0    5          1  
1    4          1  
2    4          1  
3    5          1  
4    5          1

# Step 5.  Build the Model.


**The first layer has 11 neurons and expects 11 input variables.** 

**The second hidden layer has 8 neurons.**

**The third hidden layer has 8 neurons.** 

**The output layer has 1 neuron to predict the class.** 

In [20]:
### Define the model 
model = Sequential()
model.add(Dense(11, input_dim=11, init='uniform', activation='relu'))
model.add(Dense(8, init='uniform', activation='relu'))
model.add(Dense(8, init='uniform', activation='relu')) 
model.add(Dense(1, init='uniform', activation='sigmoid'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(11, input_dim=11, activation="relu", kernel_initializer="uniform")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, activation="relu", kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, activation="relu", kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  """


# Step 6.  Compile the Model.

* **The 'loss' is the difference the predicted values and the actual values.**
* **The optimizer adjusts the weights so the loss can be reduced.**
* **A metric is a function that is used to judge the performance of the model.** 

In [0]:
### Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Step 7.  Fit the Model.

**Set the training hyperparameters.**

* **Epoch:** A full pass over all of the training dataset.

* **Batch_Size:** Denotes the subset size of the training dataset. 

In [22]:
### Train the model
model.fit(X, y, nb_epoch=200, batch_size=30)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/200
500/500 [==============================] - 0s 746us/step - loss: 0.6931 - acc: 0.5320
Epoch 2/200
500/500 [==============================] - 0s 176us/step - loss: 0.6928 - acc: 0.5340
Epoch 3/200
500/500 [==============================] - 0s 176us/step - loss: 0.6926 - acc: 0.5340
Epoch 4/200
500/500 [==============================] - 0s 170us/step - loss: 0.6924 - acc: 0.5340
Epoch 5/200
500/500 [==============================] - 0s 180us/step - loss: 0.6921 - acc: 0.5340
Epoch 6/200
500/500 [==============================] - 0s 164us/step - loss: 0.6917 - acc: 0.5340
Epoch 7/200
500/500 [==============================] - 0s 164us/step - loss: 0.6910 - acc: 0.5340
Epoch 8/200
500/500 [==============================] - 0s 189us/step - loss: 0.6902 - acc: 0.5340
Epoch 9/200
500/500 [==============================] - 0s 167us/step - loss: 0.6891 - acc: 0.5340
Epoch 10/200
500/500 [==============================] - 0s 157us/step - loss: 0.6879 - acc: 0.5340
Epoch 11/200
500/50

# Step 8.  Score the Model.

In [23]:
### Get the model accuracy
scores = model.evaluate(X, y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

500/500 [==============================] - 0s 169us/step
acc: 70.20%
