<a href="https://colab.research.google.com/github/paulgureghian/Deep_Learning_with_Keras/blob/master/CNNs_with_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://cognitiveclass.ai"><img src = "https://ibm.box.com/shared/static/9gegpsmnsoo25ikkbl4qzlvlyjbgxs5x.png" width = 400> </a>

<h1 align=center><font size = 5>Convolutional Neural Networks with Keras</font></h1>

In this lab, we will learn how to use the keras library to build convolutional neural networks. We will also use the popular MNIST dataset and we will compare our results to using a conventional neural network.


## Table of Contents

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>
      
1. <a href="#item2">Import Keras and Packages</a>   
2. <a href="#item3">Convolutional Neural Network with One Convolutional and Pooling Layers</a>  
3. <a href="#item4">Convolutional Neural Network with Two Convolutional and Pooling Layers</a>  

</font>
</div>

## Import Keras and Packages

Let's start by importing the keras libraries and the packages that we would need to build a neural network.

In [0]:
### Import Keras 
import keras
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical

When working with convolutional neural networks in particular, we will need additional packages.

In [0]:
### Import additional Keras packages
from keras.layers import Flatten                     ### To flatten data for fully connected layers
from keras.layers.convolutional import Conv2D        ### To add convolutional layers
from keras.layers.convolutional import MaxPooling2D  ### To add pooling layers

## Convolutional Network with one set of convolutional and pooling layers

In [10]:
### Import data
from keras.datasets import mnist

### Load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

### Print 'X_train' and 'X_test' 
print("X_train:\n",  X_train, '\n')
print("X_test:\n", X_test, '\n')

### Reshape to be [samples][pixels][width][height]
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1).astype('float32')
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1).astype('float32')

### Print reshaped 'X_train' and 'X_test'
print("Reshaped X_train:\n", X_train, '\n')
print("Resahped X_test:\n", X_test) 

X_train:
 [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]] 

X_test:
 [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ..

In [11]:
print(len(X_train))
print(len(X_test)) 

60000
10000


In [12]:
print(len(y_train))
print(len(y_test)) 

60000
10000


In [13]:
print("Y_train:\n" , y_train, '\n')
print("Y_test:\n" , y_test)  

Y_train:
 [5 0 4 ... 5 6 8] 

Y_test:
 [7 2 1 ... 4 5 6]


Let's normalize the pixel values to be between 0 and 1

In [14]:
### Normalize pixel values
X_train = X_train / 255 ### Normalize training data
X_test = X_test / 255   ### Normalize test data

print("X_train:\n", X_train, '\n')
print("X_test:\n", X_test) 

X_train:
 [[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.

Next, let's convert the target variable into binary categories

In [15]:
### Convert target variable to binary
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

print("Y_train:\n", y_train, '\n')
print("Y_test:\n", y_test, '\n')

num_classes = y_test.shape[1] ### Number of categories

print("Num Classes:\n", num_classes) 

Y_train:
 [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]] 

Y_test:
 [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 

Num Classes:
 10


Next, let's define a function that creates our model. Let's start with one set of convolutional and pooling layers.

In [0]:
### Define 'convolutional model()'
def convolutional_model():
    
    ### Create model
    model = Sequential()
    model.add(Conv2D(16, (5, 5), strides=(1, 1), activation='relu', input_shape=(28, 28, 1)))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    
    model.add(Flatten())
    model.add(Dense(100, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    
    ### Compile model
    model.compile(optimizer='adam', loss='categorical_crossentropy',  metrics=['accuracy'])
    
    return model

Finally, let's call the function to create the model, and then let's train it and evaluate it.

In [17]:
### Instantiate the model
model = convolutional_model()

### Fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200, verbose=2)

### Evaluate the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: {} \n Error: {}".format(scores[1], 100-scores[1]*100))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
 - 6s - loss: 0.2913 - acc: 0.9177 - val_loss: 0.1098 - val_acc: 0.9665
Epoch 2/10
 - 3s - loss: 0.0875 - acc: 0.9745 - val_loss: 0.0620 - val_acc: 0.9795
Epoch 3/10
 - 3s - loss: 0.0583 - acc: 0.9832 - val_loss: 0.0517 - val_acc: 0.9823
Epoch 4/10
 - 3s - loss: 0.0454 - acc: 0.9860 - val_loss: 0.0402 - val_acc: 0.9861
Epoch 5/10
 - 3s - loss: 0.0364 - acc: 0.9886 - val_loss: 0.0465 - val_acc: 0.9842
Epoch 6/10
 - 3s - loss: 0.0301 - acc: 0.9910 - val_loss: 0.0392 - val_acc: 0.9870
Epoch 7/10
 - 3s - loss: 0.0239 - acc: 0.9928 - val_loss: 0.0389 - val_acc: 0.9870
Epoch 8/10
 - 3s - loss: 0.0198 - acc: 0.9941 - val_loss: 0.0420 - val_acc: 0.9860
Epoch 9/10
 - 3s - loss: 0.0196 - acc: 0.9939 - val_loss: 0.0381 - val_acc: 0.9885
Epoch 10/10
 - 3s - loss: 0.0145 - acc: 0.9958 - val_loss: 0.0363 - val_acc: 0.9880
Accuracy: 0.988 
 Error: 1.2000000000000028


------------------------------------------

## Convolutional Network with two sets of convolutional and pooling layers

Let's redefine our convolutional model so that it has two convolutional and pooling layers instead of just one layer of each.

In [0]:
### Define 'convolutional model()'
def convolutional_model():
    
    ### Create model
    model = Sequential()
    model.add(Conv2D(16, (5, 5), activation='relu', input_shape=(28, 28, 1)))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    
    model.add(Conv2D(8, (2, 2), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    
    model.add(Flatten())
    model.add(Dense(100, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    
    ### Compile model
    model.compile(optimizer='adam', loss='categorical_crossentropy',  metrics=['accuracy'])
    
    return model

Now, let's call the function to create our new convolutional neural network, and then let's train it and evaluate it.

In [19]:
### Instantiate the model
model = convolutional_model()

### Fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200, verbose=2)

### Evaluate the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: {} \n Error: {}".format(scores[1], 100-scores[1]*100))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
 - 3s - loss: 0.4463 - acc: 0.8805 - val_loss: 0.1358 - val_acc: 0.9606
Epoch 2/10
 - 3s - loss: 0.1254 - acc: 0.9623 - val_loss: 0.0857 - val_acc: 0.9746
Epoch 3/10
 - 3s - loss: 0.0880 - acc: 0.9735 - val_loss: 0.0713 - val_acc: 0.9779
Epoch 4/10
 - 3s - loss: 0.0698 - acc: 0.9790 - val_loss: 0.0589 - val_acc: 0.9815
Epoch 5/10
 - 3s - loss: 0.0610 - acc: 0.9806 - val_loss: 0.0587 - val_acc: 0.9821
Epoch 6/10
 - 3s - loss: 0.0515 - acc: 0.9837 - val_loss: 0.0460 - val_acc: 0.9847
Epoch 7/10
 - 3s - loss: 0.0456 - acc: 0.9863 - val_loss: 0.0439 - val_acc: 0.9850
Epoch 8/10
 - 3s - loss: 0.0406 - acc: 0.9875 - val_loss: 0.0409 - val_acc: 0.9861
Epoch 9/10
 - 3s - loss: 0.0359 - acc: 0.9890 - val_loss: 0.0418 - val_acc: 0.9852
Epoch 10/10
 - 3s - loss: 0.0354 - acc: 0.9891 - val_loss: 0.0428 - val_acc: 0.9851
Accuracy: 0.9851 
 Error: 1.490000000000009


### Thank you for completing this lab!

This notebook was created by [Alex Aklson](https://www.linkedin.com/in/aklson/). I hope you found this lab interesting and educational. Feel free to contact me if you have any questions!

This notebook is part of a course on **edX** called *Deep Learning Fundamentals with Keras*. If you accessed this notebook outside the course, you can take this course online by clicking [here](http://cocl.us/DL0101EN_edX_Week4_LAB1).

<hr>

Copyright &copy; 2018 [IBM Developer Skills Network](https://cognitiveclass.ai/?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/).