<a href="https://colab.research.google.com/github/paulgureghian/Deep_Learning_with_Keras/blob/master/CNNs_with_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://cognitiveclass.ai"><img src = "https://ibm.box.com/shared/static/9gegpsmnsoo25ikkbl4qzlvlyjbgxs5x.png" width = 400> </a>

<h1 align=center><font size = 5>Convolutional Neural Networks with Keras</font></h1>

In this lab, we will learn how to use the keras library to build convolutional neural networks. We will also use the popular MNIST dataset and we will compare our results to using a conventional neural network.


## Table of Contents

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>
      
1. <a href="#item2">Import Keras and Packages</a>   
2. <a href="#item3">Convolutional Neural Network with One Convolutional and Pooling Layers</a>  
3. <a href="#item4">Convolutional Neural Network with Two Convolutional and Pooling Layers</a>  

</font>
</div>

## Import Keras and Packages

Let's start by importing the keras libraries and the packages that we would need to build a neural network.

In [0]:
### Import Pandas 
import pandas as pd

In [0]:
### Import Keras 
import keras
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical

When working with convolutional neural networks in particular, we will need additional packages.

In [0]:
### Import additional Keras packages
from keras.layers import Flatten                     ### To flatten data for fully connected layers
from keras.layers.convolutional import Conv2D        ### To add convolutional layers
from keras.layers.convolutional import MaxPooling2D  ### To add pooling layers

## Convolutional Layer with two sets of convolutional and pooling layers

In [18]:
### Import data
from keras.datasets import mnist

### Load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

### Print 'X_train' and 'X_test' 
print("X_train:\n",  X_train, '\n')
print("X_test:\n", X_test, '\n')

### Reshape to be [samples][pixels][width][height]
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1).astype('float32')
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1).astype('float32')

### Print reshaped 'X_train' and 'X_test'
print("Reshaped X_train:\n", X_train, '\n')
print("Resahped X_test:\n", X_test) 

X_train:
 [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]] 

X_test:
 [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ..

Let's normalize the pixel values to be between 0 and 1

In [0]:
X_train = X_train / 255 # normalize training data
X_test = X_test / 255 # normalize test data

Next, let's convert the target variable into binary categories

In [0]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

num_classes = y_test.shape[1] # number of categories

Next, let's define a function that creates our model. Let's start with one set of convolutional and pooling layers.

In [0]:
def convolutional_model():
    
    # create model
    model = Sequential()
    model.add(Conv2D(16, (5, 5), strides=(1, 1), activation='relu', input_shape=(28, 28, 1)))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    
    model.add(Flatten())
    model.add(Dense(100, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    
    # compile model
    model.compile(optimizer='adam', loss='categorical_crossentropy',  metrics=['accuracy'])
    return model

Finally, let's call the function to create the model, and then let's train it and evaluate it.

In [7]:
# build the model
model = convolutional_model()

# fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200, verbose=2)

# evaluate the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: {} \n Error: {}".format(scores[1], 100-scores[1]*100))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
 - 6s - loss: 0.2889 - acc: 0.9190 - val_loss: 0.1010 - val_acc: 0.9710
Epoch 2/10
 - 2s - loss: 0.0860 - acc: 0.9752 - val_loss: 0.0639 - val_acc: 0.9802
Epoch 3/10
 - 2s - loss: 0.0577 - acc: 0.9829 - val_loss: 0.0630 - val_acc: 0.9795
Epoch 4/10
 - 2s - loss: 0.0448 - acc: 0.9866 - val_loss: 0.0398 - val_acc: 0.9861
Epoch 5/10
 - 2s - loss: 0.0360 - acc: 0.9891 - val_loss: 0.0372 - val_acc: 0.9876
Epoch 6/10
 - 2s - loss: 0.0300 - acc: 0.9909 - val_loss: 0.0350 - val_acc: 0.9874
Epoch 7/10
 - 2s - loss: 0.0250 - acc: 0.9923 - val_loss: 0.0340 - val_acc: 0.9887
Epoch 8/10
 - 2s - loss: 0.0209 - acc: 0.9935 - val_loss: 0.0359 - val_acc: 0.9877
Epoch 9/10
 - 2s - loss: 0.0175 - acc: 0.9948 - val_loss: 0.0420 - val_acc: 0.9872
Epoch 10/10
 - 2s - loss: 0.0143 - acc: 0.9956 - val_loss: 0.0351 - val_acc: 0.9877
Accuracy: 0.9877 
 Error: 1.230000000000004


------------------------------------------

## Convolutional Layer with two sets of convolutional and pooling layers

Let's redefine our convolutional model so that it has two convolutional and pooling layers instead of just one layer of each.

In [0]:
def convolutional_model():
    
    # create model
    model = Sequential()
    model.add(Conv2D(16, (5, 5), activation='relu', input_shape=(28, 28, 1)))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    
    model.add(Conv2D(8, (2, 2), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    
    model.add(Flatten())
    model.add(Dense(100, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    
    # Compile model
    model.compile(optimizer='adam', loss='categorical_crossentropy',  metrics=['accuracy'])
    return model

Now, let's call the function to create our new convolutional neural network, and then let's train it and evaluate it.

In [9]:
# build the model
model = convolutional_model()

# fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200, verbose=2)

# evaluate the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: {} \n Error: {}".format(scores[1], 100-scores[1]*100))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
 - 3s - loss: 0.4869 - acc: 0.8538 - val_loss: 0.1513 - val_acc: 0.9559
Epoch 2/10
 - 2s - loss: 0.1230 - acc: 0.9639 - val_loss: 0.0813 - val_acc: 0.9744
Epoch 3/10
 - 2s - loss: 0.0844 - acc: 0.9741 - val_loss: 0.0679 - val_acc: 0.9788
Epoch 4/10
 - 2s - loss: 0.0676 - acc: 0.9794 - val_loss: 0.0631 - val_acc: 0.9796
Epoch 5/10
 - 2s - loss: 0.0572 - acc: 0.9825 - val_loss: 0.0468 - val_acc: 0.9860
Epoch 6/10
 - 2s - loss: 0.0494 - acc: 0.9851 - val_loss: 0.0468 - val_acc: 0.9844
Epoch 7/10
 - 2s - loss: 0.0447 - acc: 0.9866 - val_loss: 0.0455 - val_acc: 0.9848
Epoch 8/10
 - 2s - loss: 0.0408 - acc: 0.9875 - val_loss: 0.0444 - val_acc: 0.9853
Epoch 9/10
 - 2s - loss: 0.0362 - acc: 0.9890 - val_loss: 0.0352 - val_acc: 0.9885
Epoch 10/10
 - 2s - loss: 0.0323 - acc: 0.9900 - val_loss: 0.0397 - val_acc: 0.9866
Accuracy: 0.9866 
 Error: 1.3400000000000034


### Thank you for completing this lab!

This notebook was created by [Alex Aklson](https://www.linkedin.com/in/aklson/). I hope you found this lab interesting and educational. Feel free to contact me if you have any questions!

This notebook is part of a course on **edX** called *Deep Learning Fundamentals with Keras*. If you accessed this notebook outside the course, you can take this course online by clicking [here](http://cocl.us/DL0101EN_edX_Week4_LAB1).

<hr>

Copyright &copy; 2018 [IBM Developer Skills Network](https://cognitiveclass.ai/?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/).